### ISSUE TITLE
Invalid field format for year of death (yod) error.

### ISSUE THREAD

**Issue by odeke** [nafiesl/silsilah#25]
The user profile form with the year of death field only accepts a year e.g 2000 and the database only accepts date format. I solved this by changing the DB field for yod to an int in the users table.

**Comment by nafiesl** [comment]
Hi @odeke, thanks for your information. I will check that issue.

**Comment by nafiesl** [comment]
Hi @odeke, my apologize for late response. You were right, the `yod` column on `users` table is using date data type. I believe we need to use `year` data type instead of `int`.

I have fix this issue by changing the column data type to `year` in this commit: 3da89bf.

For existing database, you can run this sql command to apply this user table changes:
> Don't forget to backup your database before run this sql command.
```sql
ALTER TABLE `users`
	CHANGE COLUMN `yod` `yod` YEAR NULL DEFAULT NULL AFTER `dod`;
```

**Comment by odeke** [comment]
glad to help! Keep going, this is the neatest genealogy project out there.
I will share my finished edition for your review.

**Comment by nafiesl** [comment]
Sure @odeke, good to know you were creating one, too. I would be glad to wait. 👍
