### ISSUE TITLE
Suggested modification of a person's identity 

### ISSUE THREAD

**Issue by David-Baron** [nafiesl/silsilah#75]
For a modern genealogy:
A person can have one father, A person can have one mother: this is only true on the day of his birth, thereafter he can be adopted.
A person can have one parent: so this becomes false.
Enter Name and Gender: this is true on the day of his birth only, thereafter he may change his name or gender and therefore the death information will no longer correspond with the birth.

This is just to give you a more current hierarchy.

**Comment by nafiesl** [comment]
Hello, @David-Baron.

I think I do not really get what you say, but here is my understanding:
1. A person should not have a parent, because it is already represented by their father and mother data.
2. Name and Gender on birth can be different with their death data.

Let me know if my understandings are different from your point.

---

Here are my thought on those 2 points:

1. Father and mother data will represent the person's actual birth. The parent data can be different (mother and father) if they are adopted.

    For example: 
    - Person: Andy
    - His father: Thomas
    - His mother: Sisca
    - Parents couple: Thomas and Sisca
    - Another couple: Jerry and Deasy

    Here are some scenarios:
    a. If Andy's parent data is Thomas and Sisca, then they should be the real parent of Andy. Correct?
    b. If Andy's parent data is Jerry and Deasy, then Andy has been adopted by them

    Based on point b, we can set on Andy: Thomas as the father, Sisca as the mother, "Jerry and Deasy" (couple) as the parent. What do you think, @David-Baron?

2. Name and Gender on birth can be different with their death data, I think the current feature has no issue with this. As we can the person's gender and name anytime on the person edit page. Any concern with this feature, @David-Baron?

**Comment by David-Baron** [comment]
@nafiesl Hello!
I would say ... yes and no.

Father / mother and parents it's ambiguous, in some countries it's the same thing. Adoptive parents are also called father / mother.

For the change of sex, I do not agree because if on the identity of a person and for example you have a man because she has changed sex, if you search for the birth, you will look for a man not a woman if not specified. This is why the sex should be written in the event (birth or death), not in the identity.

I was just seeing what was written in the readme.

**Comment by nafiesl** [comment]
Hi @David-Baron,

1. Adoptive parents are also called father / mother <-- I agree, In my country, too. But I don't see this reason made us need to change anything on the project. What do you suggest?

2. So you want the person's gender to be separated into: "the birth gender" and "the death gender". Is that what you mean?

**Comment by haniefss** [comment]
> 
> 
> Hi @David-Baron,
> 
>     1. Adoptive parents are also called father / mother <-- I agree, In my country, too. But I don't see this reason made us need to change anything on the project. What do you suggest?
> 
>     2. So you want the person's gender to be separated into: "the birth gender" and "the death gender". Is that what you mean?

#2 I think we can just change **Gender** to **Sex** and be done with it. @nafiesl nowadays apparently people can choose whatever **gender** they like (such natural born male prefer to be called a woman, etc).

**Comment by lcallif** [comment]
What if you had:
Birth Gender
Current Gender
The Current Gender would end up being the Death Gender.
 

 

 

Hi @David-Baron,
1. Adoptive parents are also called father / mother <-- I agree, In my country, too. But I don't see this reason made us need to change anything on the project. What do you suggest?
 
2. So you want the person's gender to be separated into: "the birth gender" and "the death gender". Is that what you mean?
#2 I think we can just change Gender to Sex and be done with it. @nafiesl nowadays apparently people can choose whatever gender they like (such natural born male prefer to be called a woman, etc).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by David-Baron** [comment]
I don't know what's in your app. But change your readme if you want more users .

**Comment by bipul-kumar** [comment]
Hi @nafiesl 
I am learning laravel so can you tell me how to add wife information in family chart and tree .

**Comment by nafiesl** [comment]
Hi guys, thanks for contributing to this issue, I decided to not change anything regarding father/mother/parent terms and gender/sex terms.

I am closing this issue, thank you very much.
